### ISSUE TITLE
missing libgssapi_krb5.so.2

### ISSUE THREAD

**Issue by Edzilla2000** [jacobalberty/cups-docker#1]
I tried running your image, but I get this error on container startup: 
`/usr/sbin/cupsd: error while loading shared libraries: libgssapi_krb5.so.2: cannot open shared object file: No such file or directory`

**Comment by jacobalberty** [comment]
Sorry bout that, there was a missing package, I always use this image with the hplip drivers and the script for that apparently installs that package.

I've identified the missing package, about to check in a fix for it and rebuild on the hub, I'll update this when it's built on the hub

**Comment by jacobalberty** [comment]
This should be fixed in the latest images on the hub.

**Comment by Edzilla2000** [comment]
This does indeed fix it, thank you for the very fast fix
